name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          username: ${{ github.actor }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: pingwinator/sysbench:latest
          registry: docker.pkg.github.com
          repository: pingwinator/sysbench/sysbench
          tag_with_ref: true
